// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK1ZNUg7uTSxWtP3Y0zAPRQkYhZNdmkB8',
    appId: '1:405250285596:web:6ee3f77dbc748d223a7fd9',
    messagingSenderId: '405250285596',
    projectId: 'redbus-atts',
    authDomain: 'redbus-atts.firebaseapp.com',
    storageBucket: 'redbus-atts.firebasestorage.app',
    measurementId: 'G-J35C7YWEK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ_tw1Pt8p7VGN3tfPyDQ3qrL0NxHeBSM',
    appId: '1:405250285596:android:9fa5016f7c227a933a7fd9',
    messagingSenderId: '405250285596',
    projectId: 'redbus-atts',
    storageBucket: 'redbus-atts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj-pRdxjota0j3ZHZT5ueat_2GC0lmhfA',
    appId: '1:405250285596:ios:4fa34c42bfb008613a7fd9',
    messagingSenderId: '405250285596',
    projectId: 'redbus-atts',
    storageBucket: 'redbus-atts.firebasestorage.app',
    iosBundleId: 'com.example.redBusAtts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj-pRdxjota0j3ZHZT5ueat_2GC0lmhfA',
    appId: '1:405250285596:ios:4fa34c42bfb008613a7fd9',
    messagingSenderId: '405250285596',
    projectId: 'redbus-atts',
    storageBucket: 'redbus-atts.firebasestorage.app',
    iosBundleId: 'com.example.redBusAtts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK1ZNUg7uTSxWtP3Y0zAPRQkYhZNdmkB8',
    appId: '1:405250285596:web:176b032b0f7fb3c33a7fd9',
    messagingSenderId: '405250285596',
    projectId: 'redbus-atts',
    authDomain: 'redbus-atts.firebaseapp.com',
    storageBucket: 'redbus-atts.firebasestorage.app',
    measurementId: 'G-P90VN4YS0V',
  );
}
